# Generated by Django 4.1.2 on 2022-10-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Accessories', 'Accessories'), ('Camera', 'Camera'), ('Headphone', 'Headphone'), ('mobile', 'mobile')], max_length=100),
        ),
    ]
