# Generated by Django 4.1.2 on 2022-10-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Accessories', 'Accessories'), ('Camera', 'Camera'), ('Headphone', 'Headphone'), ('Smartphone', 'Smartphone')], max_length=100),
        ),
    ]
