# Generated by Django 4.1.2 on 2022-10-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
